name: Update Channels



jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb wget unzip

      - name: Install Google Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install seleniumbase undetected-chromedriver

      - name: Run update script (headless with Xvfb)
        run: |
          DISPLAY=:99 xvfb-run -a python scripts/update_channels_headless.py


      - name: Commit and push channels.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add channels.json
          git commit -m "Auto-update channels.json" || echo "No changes"
          git push
